from FieldTests import FieldTests
CSV = raw_input('Enter CSV file name: ')

with open(CSV) as csvfile:
    test = FieldTests(csvfile)
    test.completefieldtest("Preheader","content","false","true","false","true","true")
    test.completefieldtest("Logo and Contact","content","false","true","false","false","true")
    test.completefieldtest("Banner","content","false","true","false","true","true")
    test.completefieldtest("Body with Sidebar","content","false","true","false","false","true")
    test.completefieldtest("Body without Sidebar","content","false","true","false","false","true")
    test.completefieldtest("PVP","content","false","true","false","false","true")
    test.completefieldtest("Partner Address with Social","content","false","true","false","false","true")
    test.completefieldtest("Footer","content","false","true","false","false","true")
    test.completefieldtest("Footer Code","content","false","true","false","false","true")
    test.completefieldtest("Accent Color","colorpicker","false","true","false","false","true")
    test.completefieldtest("Accent CTA Color","colorpicker","false","true","false","false","true")
    test.completefieldtest("View Online","edit","true","false","false","true","true")
    test.completefieldtest("Logo","embeddedimage","false","true","false","false","true")
    test.completefieldtest("Partner Display Name","edit","false","true","false","false","true")
    test.completefieldtest("Partner Phone","edit","false","true","false","false","true")
    test.completefieldtest("Partner Email","emailAddress","false","true","true","false","true")
    test.completefieldtest("Partner URL Text","edit","false","true","false","false","true")
    test.completefieldtest("Partner URL","url","false","true","false","false","true")
    test.completefieldtest("Banner Image","embeddedimage","true","false","false","true","true")
    test.completefieldtest("Banner Image Alt","edit","true","false","false","true","true")
    test.completefieldtest("Email Options","checkbox","true","false","true","true","true")
    test.completefieldtest("Title","edit","true","true","false","true","true")
    test.completefieldtest("Greeting Option","radio","false","true","false","false","true")
    test.completefieldtest("Greeting Text","edit","false","true","false","false","true")
    test.completefieldtest("Greeting Text DE","edit","false","true","false","false","true")
    test.completefieldtest("First Name Field","edit","false","true","false","false","true")
    test.completefieldtest("Body Copy","richtext","true","true","false","true","true")
    test.completefieldtest("Body Copy CTA","edit","true","true","false","true","true")
    test.completefieldtest("Signature Option","radio","false","true","false","false","true")
    test.completefieldtest("Signature Block","richtext","false","true","false","false","true")
    test.completefieldtest("Signature Block DE","richtext","false","true","false","false","true")
    test.completefieldtest("Sidebar Options","checkbox","true","false","true","true","true")
    test.completefieldtest("Sidebar Image","embeddedimage","true","false","false","true","true")
    test.completefieldtest("Sidebar Copy","richtext","true","true","false","true","true")
    test.completefieldtest("Sidebar CTA","edit","true","true","false","true","true")
    test.completefieldtest("Partner Value Proposition","richtext","false","true","false","false","true")
    test.completefieldtest("Social Icons","checkbox","false","true","false","false","true")
    test.completefieldtest("Twitter URL","url","false","true","false","false","true")
    test.completefieldtest("Facebook URL","url","false","true","false","false","true")
    test.completefieldtest("LinkedIn URL","url","false","true","false","false","true")
    test.completefieldtest("Google URL","url","false","true","false","false","true")
    test.completefieldtest("YouTube URL","url","false","true","false","false","true")
    test.completefieldtest("RSS URL","url","false","true","false","false","true")
    test.completefieldtest("Privacy Policy Option","radio","false","true","false","false","true")
    test.completefieldtest("Privacy Policy URL","url","false","true","false","false","true")
    test.completefieldtest("Terms and Conditions Option","radio","false","true","false","false","true")
    test.completefieldtest("Terms and Conditions URL","url","false","true","false","false","true")
    test.completefieldtest("Landing Page Headline","edit","true","true","false","true","true")
    test.completefieldtest("Landing Page Body Copy","richtext","true","true","false","true","true")
    test.completefieldtest("Landing Page Image Option","radio","true","false","true","true","true")
    test.completefieldtest("Landing Page Image","embeddedimage","true","false","false","true","true")
    test.completefieldtest("Confirmation Page Headline","edit","true","true","false","true","true")
    test.completefieldtest("Confirmation Page Body Copy","richtext","true","true","false","true","true")
    test.completefieldtest("Confirmation Button CTA","edit","true","false","false","true","true")
    test.completefieldtest("CTA Link Option","radio","false","false","false","true","true")
    test.completefieldtest("Asset URL","url","true","false","false","true","true")
    test.completefieldtest("Secondary Asset URL","url","true","false","false","true","true")
    test.completefieldtest("Secondary Body CTA","edit","true","true","false","true","true")
    test.completefieldtest("Inline Address","edit","false","true","false","false","true")
    test.completefieldtest("Landing Page Footer Code","content","false","true","false","false","true")